# Generated by Django 3.1.3 on 2020-12-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='product',
            new_name='service',
        ),
    ]
