# Generated by Django 3.1.3 on 2021-01-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20210105_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='timestamp',
            new_name='date',
        ),
    ]
