# Generated by Django 3.1.3 on 2021-01-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20210114_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='select_date',
            field=models.DateTimeField(verbose_name='Selected Date (mm/dd/yyyy)'),
        ),
    ]
