# Generated by Django 3.1.3 on 2021-01-14 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20210114_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='select_date',
        ),
    ]
