# Generated by Django 3.1.3 on 2021-01-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_orderlineitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='select_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Selected Date (dd-mm-yyyy H:m)'),
        ),
    ]
