# Generated by Django 3.1.3 on 2021-01-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('name_client', models.CharField(max_length=254)),
                ('likes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('views', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_6', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_7', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_8', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_9', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_10', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_11', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_12', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_13', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_14', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_15', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_16', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_17', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_18', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_19', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_20', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_21', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_22', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_23', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_24', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_25', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_26', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_slide_27', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
