# Generated by Django 3.1.3 on 2021-01-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210105_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='select_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='timestamp',
        ),
    ]
